@hostname=localhost
@port=7153
@rootUrl = https://{{hostname}}:{{port}}

GET {{rootUrl}}/foods?query=pizza&number=5

#
GET {{rootUrl}}/foods?query=pizza&number=1

#
GET {{rootUrl}}/foods?query=pizza&number=100

#
GET {{rootUrl}}/foods?query=burger&number=20